version: '3.8'

services:
  react-app:
    build:
      context: ./react-app  # Path to your React app
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Map to Nginx port
    depends_on:
      - api

  api:
    build:
      context: ./dotnet-app  # Path to your .NET app
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=YourDatabase;User=sa;Password=yourStrong(!)Password;

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: Sugan@123
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:

